In [12]:
import numpy as np

np.random.seed(42)

A = np.random.normal(40, 12, (1000, 5))

print("Shape:", A.shape)
print("Dtype:", A.dtype)
print("Memory:", A.nbytes, "bytes")

A = A.astype(np.float32)

print("New dtype:", A.dtype)
print("New memory:", A.nbytes, "bytes")

Shape: (1000, 5)
Dtype: float64
Memory: 40000 bytes
New dtype: float32
New memory: 20000 bytes


In [13]:
mean = A.mean(axis=0)
std = A.std(axis=0)

Z = (A - mean) / std

print("Mean of columns:")
print(Z.mean(axis=0))

print("Standard deviation of columns:")
print(Z.std(axis=0))

Mean of columns:
[-2.1434539e-06  1.3412238e-06  2.1815300e-07 -1.9633173e-06
 -8.1747771e-07]
Standard deviation of columns:
[0.9999991  0.99999994 0.9999998  1.0000002  0.9999998 ]


In [14]:
import numpy as np

def minmax(X, axis):
    minimum = X.min(axis=axis, keepdims=True)
    maximum = X.max(axis=axis, keepdims=True)
    return (X - minimum) / (maximum - minimum)

# Define X using a slice of A as done in the later cells
X = A[:200]

result0 = minmax(X, 0)

print("Axis 0 minimum:", result0.min(axis=0))
print("Axis 0 maximum:", result0.max(axis=0))
result1 = minmax(X, 1)

print("Axis 1 minimum:", result1.min(axis=1))
print("Axis 1 maximum:", result1.max(axis=1))

Axis 0 minimum: [0. 0. 0. 0. 0.]
Axis 0 maximum: [1. 1. 1. 1. 1.]
Axis 1 minimum: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
Axis 1 maximum: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.


In [15]:
np.random.seed(42)

mask = np.random.random(A.shape) < 0.05

A[mask] = np.nan

column_means = np.nanmean(A, axis=0)

for i in range(A.shape[1]):
    missing = np.isnan(A[:, i])
    A[missing, i] = column_means[i]

print(np.isnan(A).sum() == 0)

True


In [16]:
mean = A.mean(axis=0)
std = A.std(axis=0)

outliers = np.abs(A - mean) > 3 * std

median = np.median(A, axis=0)

for i in range(A.shape[1]):
    A[outliers[:, i], i] = median[i]

print("Outliers replaced")

Outliers replaced


In [17]:
X = A[:200]

X1 = X[:, np.newaxis, :]
X2 = X[np.newaxis, :, :]

difference = X1 - X2

distance_matrix = np.sqrt(
    (difference ** 2).sum(axis=2))
print(distance_matrix.shape)
print(np.allclose(np.diag(distance_matrix), 0))
print(np.allclose(distance_matrix, distance_matrix.T))

(200, 200)
True
True


In [18]:
import numpy as np


distance_matrix_copy = distance_matrix.copy()
np.fill_diagonal(distance_matrix_copy, np.inf)

# finding 5 smallest distance indices for each row
nearest_5_indices = np.argpartition(distance_matrix_copy, kth=5, axis=1)[:, :5]

print("Shape:", nearest_5_indices.shape)
print("Sample of first 5 rows nearest neighbors:\n", nearest_5_indices[:5])

Shape: (200, 5)
Sample of first 5 rows nearest neighbors:
 [[185 180 116 182 120]
 [199 114  17  70  31]
 [  3  99  37 145 132]
 [132  99   2 145  39]
 [160 143 158 102  43]]


In [19]:

%%time
import numpy as np
np.random.seed(42)
numbers = np.random.randint(0, 100, size=1_000_000)

counts_numpy = np.bincount(numbers)
print("First 10 counts (NumPy):", counts_numpy[:10])

numbers_list = numbers.tolist()
counts_python = [0] * 100
for num in numbers_list:
    counts_python[num] += 1

print("First 10 counts (Python):", counts_python[:10])
print("Results match:", list(counts_numpy) == counts_python)

First 10 counts (NumPy): [ 9995 10049 10103  9927 10130 10010  9956  9968 10074 10028]
First 10 counts (Python): [9995, 10049, 10103, 9927, 10130, 10010, 9956, 9968, 10074, 10028]
Results match: True
CPU times: user 167 ms, sys: 7.81 ms, total: 175 ms
Wall time: 177 ms


In [20]:
import numpy as np
import pandas as pd

from numpy.lib.stride_tricks import sliding_window_view

x = np.random.randn(10000)

windows = sliding_window_view(x, 10)

print("Shape:", windows.shape)

numpy_means = windows.mean(axis=1)

pandas_means = pd.Series(x).rolling(10).mean().dropna().to_numpy()

print("Results are same:", np.allclose(numpy_means, pandas_means))

Shape: (9991, 10)
Results are same: True


In [21]:
import numpy as np

X = np.random.randn(12, 8)

X = X.reshape(4, 3, 8)

result = X.mean(axis=1)

print(result.shape)

(4, 8)


In [22]:
import numpy as np

np.save("clean.npy", A)

loaded_A = np.load("clean.npy")

assert np.array_equal(loaded_A, A)

print("Array saved, loaded, and verified successfully.")

#np.save()        saves A as clean.npy
#np.load()        loads it back
#np.array_equal() checks both arrays are identical


Array saved, loaded, and verified successfully.
